/**
 * 图标语义名 —— 唯一入口 Icon 组件消费；业务代码禁止直接 import 图标库。
 * 名称表达「语义」而非「字形」，替换图标库时只改 Icon.tsx 一处映射。
 */
export type IconName =
  | 'plus'
  | 'trash'
  | 'edit'
  | 'save'
  | 'check'
  | 'close'
  | 'settings'
  | 'chevronDown'
  | 'chevronRight'
  | 'chevronLeft'
  | 'chevronUp'
  | 'search'
  | 'filter'
  | 'warning'
  | 'info'
  | 'error'
  | 'user'
  | 'users'
  | 'chapter'
  | 'foreshadow'
  | 'plotArc'
  | 'recover'
  | 'jump'
  | 'retry'
  | 'view'
  | 'model'
  | 'export'
  | 'stats'
  | 'outline'
  | 'world'
  | 'book'
  | 'library'
  | 'more'
  | 'arrowRight'
  | 'loader'
  | 'archive'
  | 'key'
  | 'plug'
  | 'target'
  | 'calendar'
  | 'trendingUp'
  | 'bold'
  | 'italic'
  | 'undo'
  | 'redo'
  | 'collapseLeft'
  | 'collapseRight'
  | 'focus'
  | 'folderPlus'
  | 'filePlus'
  | 'externalLink'
  | 'quote'
  | 'layers'
  | 'globe'
  | 'clock'
  | 'copy'
  | 'download'
  | 'up'
  | 'eye'
  | 'link'
  | 'history'
  | 'list'
  | 'activity'
  | 'tag'
  | 'dot'
  | 'hash'
  | 'table'
  | 'bookmark'
  /** AI 相关语义名（对话式建设定 / 选题向导） */
  | 'sparkles'
  | 'send'
  | 'chat'
  | 'lightbulb'
  /** 外观 / 主题相关语义名（主题选择器） */
  | 'palette'
  | 'sun'
  | 'moon'
  | 'moonStar'
  | 'leaf'
  | 'monitor'
  | 'bookOpen'
  /** 质检（一致性审校 / 去 AI 味 / 敏感词） */
  | 'audit';

/** 徽标 / 标签视觉变体（对齐 design-tokens 的 --color-* 语义层） */
export type BadgeVariant =
  | 'neutral'
  | 'primary'
  | 'accent'
  | 'danger'
  | 'warning'
  | 'success'
  | 'aging';

export type ButtonVariant = 'primary' | 'secondary' | 'ghost' | 'accent' | 'danger';
export type ButtonSize = 'sm' | 'md' | 'lg';
export type IconSize = 16 | 20 | 24;
